import type { Agent, AgentCategory } from "./types"

// Create agent objects from the JSON data
export const horizontalAgents: Agent[] = [
  {
    id: "finance",
    name: "Finance Agent",
    category: "horizontal",
    type: "Finance",
    description:
      "Supports financial teams with real-time reporting, analysis, budgeting, and compliance monitoring to optimize fiscal performance.",
    avatar: "/financial-growth-chart.png",
    price: 15000,
    timeInWeeks: 6,
    defaultSelected: true,
    resources: [
      { role: "AI Engineer", percentage: 40 },
      { role: "Finance SME", percentage: 30 },
      { role: "Data Engineer", percentage: 20 },
      { role: "QA", percentage: 10 },
    ],
    tasks: [
      "Financial Report",
      "Offset Report",
      "Financial Consolidation",
      "Alarms and Alerts",
      "Real Time Insights",
      "Predictive Analysis",
      "Budgeting and Forecasting Assistant",
      "Expense Management Advisor",
      "Risk Analysis and Compliance Monitor",
    ],
    services: [
      {
        id: "finance-1",
        name: "Financial reporting and analysis automation",
        description:
          "Automate the generation and analysis of financial reports using AI to identify trends and anomalies.",
        timeInWeeks: 1.5,
        cost: 3500,
        resources: [
          { role: "AI Engineer", percentage: 50 },
          { role: "Finance SME", percentage: 50 },
        ],
      },
      {
        id: "finance-2",
        name: "Budget forecasting and planning",
        description:
          "AI-powered budget forecasting that uses historical data and market trends to predict future financial needs.",
        timeInWeeks: 2,
        cost: 4000,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Finance SME", percentage: 40 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
      {
        id: "finance-3",
        name: "Expense management and optimization",
        description:
          "Intelligent expense tracking and management with automated categorization and optimization recommendations.",
        timeInWeeks: 1,
        cost: 2500,
        resources: [
          { role: "AI Engineer", percentage: 30 },
          { role: "Finance SME", percentage: 40 },
          { role: "Data Engineer", percentage: 30 },
        ],
      },
      {
        id: "finance-4",
        name: "Cash flow prediction and management",
        description: "Predict cash flow patterns and provide recommendations for optimal cash management strategies.",
        timeInWeeks: 1.5,
        cost: 3000,
        resources: [
          { role: "AI Engineer", percentage: 50 },
          { role: "Finance SME", percentage: 30 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
      {
        id: "finance-5",
        name: "Investment portfolio analysis",
        description:
          "AI-driven analysis of investment portfolios with risk assessment and optimization recommendations.",
        timeInWeeks: 2,
        cost: 4500,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Finance SME", percentage: 40 },
          { role: "QA", percentage: 20 },
        ],
      },
      {
        id: "finance-6",
        name: "Financial risk assessment",
        description:
          "Identify and quantify financial risks using AI models trained on historical data and market patterns.",
        timeInWeeks: 1.5,
        cost: 3500,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Finance SME", percentage: 40 },
          { role: "QA", percentage: 20 },
        ],
      },
    ],
    dependencies: [
      {
        id: "finance-rag",
        name: "Finance-specific RAG",
        description: "Specialized Retrieval Augmented Generation for financial documents and data",
        timeInWeeks: 2,
        cost: 8000,
        resources: [
          { role: "AI Engineer", percentage: 60 },
          { role: "Data Engineer", percentage: 40 },
        ],
        required: true,
      },
      {
        id: "finance-data-integration",
        name: "Financial Data Integration",
        description: "Integration with financial systems and databases",
        timeInWeeks: 1,
        cost: 5000,
        resources: [
          { role: "Data Engineer", percentage: 70 },
          { role: "Backend Developer", percentage: 30 },
        ],
      },
    ],
  },
  {
    id: "hr",
    name: "HR Agent",
    category: "horizontal",
    type: "Human Resources",
    description:
      "Empowers HR departments to streamline employee lifecycle management, performance tracking, and workforce insights.",
    avatar: "/human-resources-team.png",
    price: 12000,
    timeInWeeks: 5,
    resources: [
      { role: "AI Engineer", percentage: 40 },
      { role: "HR SME", percentage: 30 },
      { role: "Data Engineer", percentage: 20 },
      { role: "QA", percentage: 10 },
    ],
    tasks: [
      "Automated Career Pathing and Promotion Eligibility",
      "Employee Survey Distribution and Analysis",
      "Workforce Productivity Reports",
      "Onboarding Assistant",
      "Personalized Learning Advisor",
      "Employee Sentiment Analysis",
      "Performance Review Assistant",
      "Payroll and Benefits Analysis",
    ],
    services: [
      {
        id: "hr-1",
        name: "Recruitment and candidate screening",
        description: "AI-powered screening of resumes and applications to identify the most qualified candidates.",
        timeInWeeks: 1.5,
        cost: 3000,
        resources: [
          { role: "AI Engineer", percentage: 50 },
          { role: "HR SME", percentage: 50 },
        ],
      },
      {
        id: "hr-2",
        name: "Employee onboarding automation",
        description: "Streamline the onboarding process with automated document processing and personalized guidance.",
        timeInWeeks: 1,
        cost: 2500,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "HR SME", percentage: 40 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
      {
        id: "hr-3",
        name: "Performance review management",
        description: "AI-assisted performance reviews with data-driven insights and recommendation generation.",
        timeInWeeks: 1.5,
        cost: 3000,
        resources: [
          { role: "AI Engineer", percentage: 30 },
          { role: "HR SME", percentage: 50 },
          { role: "QA", percentage: 20 },
        ],
      },
      {
        id: "hr-4",
        name: "Employee engagement analysis",
        description:
          "Analyze employee feedback and behavior patterns to identify engagement trends and improvement opportunities.",
        timeInWeeks: 1.5,
        cost: 3000,
        resources: [
          { role: "AI Engineer", percentage: 50 },
          { role: "HR SME", percentage: 30 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
      {
        id: "hr-5",
        name: "Learning and development recommendations",
        description: "Personalized learning recommendations based on employee skills, goals, and company needs.",
        timeInWeeks: 1,
        cost: 2500,
        resources: [
          { role: "AI Engineer", percentage: 60 },
          { role: "HR SME", percentage: 40 },
        ],
      },
      {
        id: "hr-6",
        name: "HR policy and compliance management",
        description: "AI-powered monitoring and management of HR policies and compliance requirements.",
        timeInWeeks: 1.5,
        cost: 3000,
        resources: [
          { role: "AI Engineer", percentage: 30 },
          { role: "HR SME", percentage: 50 },
          { role: "QA", percentage: 20 },
        ],
      },
    ],
    dependencies: [
      {
        id: "hr-rag",
        name: "HR Document RAG",
        description: "Retrieval Augmented Generation for HR policies, handbooks, and employee data",
        timeInWeeks: 1.5,
        cost: 6000,
        resources: [
          { role: "AI Engineer", percentage: 60 },
          { role: "Data Engineer", percentage: 40 },
        ],
        required: true,
      },
    ],
  },
  {
    id: "customer-support",
    name: "Customer Support Agent",
    category: "horizontal",
    type: "Customer Support",
    description:
      "Enhances customer service operations through predictive support, multi-channel automation, and real-time engagement insights.",
    avatar: "/helpful-support-team.png",
    price: 14000,
    timeInWeeks: 5,
    resources: [
      { role: "AI Engineer", percentage: 40 },
      { role: "Customer Support SME", percentage: 30 },
      { role: "Data Engineer", percentage: 20 },
      { role: "QA", percentage: 10 },
    ],
    tasks: [
      "Predictive Support for Issue Prevention",
      "Dynamic FAQ and Knowledge Base Updating",
      "Real-Time Multi-Channel Response Automation",
      "Customer Care Assistant",
      "Proactive Engagement Advisor",
      "Guided Setup and Troubleshooting Assistant",
      "360-Degree Customer View",
      "Advanced Sentiment and Escalation Analysis",
      "Self-Service Insights and Optimization",
    ],
    services: [
      {
        id: "cs-1",
        name: "24/7 automated customer support",
        description:
          "AI-powered chatbot that provides round-the-clock customer support with natural language understanding.",
        timeInWeeks: 2,
        cost: 4500,
        resources: [
          { role: "AI Engineer", percentage: 60 },
          { role: "Customer Support SME", percentage: 30 },
          { role: "QA", percentage: 10 },
        ],
      },
      {
        id: "cs-2",
        name: "Ticket classification and routing",
        description: "Automatically classify and route support tickets to the appropriate department or specialist.",
        timeInWeeks: 1,
        cost: 2500,
        resources: [
          { role: "AI Engineer", percentage: 50 },
          { role: "Customer Support SME", percentage: 30 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
      {
        id: "cs-3",
        name: "Customer sentiment analysis",
        description: "Analyze customer interactions to identify sentiment and emotional trends for improved service.",
        timeInWeeks: 1.5,
        cost: 3000,
        resources: [
          { role: "AI Engineer", percentage: 60 },
          { role: "Customer Support SME", percentage: 20 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
      {
        id: "cs-4",
        name: "Knowledge base management",
        description:
          "AI-powered knowledge base that continuously learns from customer interactions and support resolutions.",
        timeInWeeks: 1.5,
        cost: 3500,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Customer Support SME", percentage: 40 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
      {
        id: "cs-5",
        name: "Customer journey optimization",
        description: "Analyze and optimize customer journeys to improve satisfaction and reduce support needs.",
        timeInWeeks: 2,
        cost: 4000,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Customer Support SME", percentage: 40 },
          { role: "QA", percentage: 20 },
        ],
      },
    ],
    dependencies: [
      {
        id: "cs-rag",
        name: "Customer Support RAG",
        description: "Retrieval Augmented Generation for customer support knowledge base and FAQs",
        timeInWeeks: 1.5,
        cost: 7000,
        resources: [
          { role: "AI Engineer", percentage: 60 },
          { role: "Data Engineer", percentage: 40 },
        ],
        required: true,
      },
      {
        id: "cs-integration",
        name: "Support System Integration",
        description: "Integration with existing customer support platforms and ticketing systems",
        timeInWeeks: 1,
        cost: 4000,
        resources: [
          { role: "Data Engineer", percentage: 60 },
          { role: "Backend Developer", percentage: 40 },
        ],
      },
    ],
  },
  {
    id: "marketing-sales",
    name: "Marketing & Sales Agent",
    category: "horizontal",
    type: "Marketing & Sales",
    description:
      "Drives growth by automating lead generation, campaign tracking, and sales forecasting with market and competitor insights.",
    avatar: "/marketing-sales-icon.png",
    price: 16000,
    timeInWeeks: 6,
    resources: [
      { role: "AI Engineer", percentage: 40 },
      { role: "Marketing SME", percentage: 30 },
      { role: "Data Engineer", percentage: 20 },
      { role: "QA", percentage: 10 },
    ],
    tasks: [
      "Lead Generation and Qualification Automation",
      "Market Trend Analysis and Insights",
      "Dynamic Campaign Performance Tracking",
      "Real-Time Sales Pipeline Monitoring",
      "Predictive Sales Forecasting",
      "Competitor Analysis and Benchmarking",
      "Automated Customer Segmentation",
      "Sales Content and Proposal Automation",
    ],
    services: [
      {
        id: "marketing-1",
        name: "Lead generation and qualification",
        description: "AI-powered lead generation and qualification to identify high-potential prospects.",
        timeInWeeks: 2,
        cost: 4500,
        resources: [
          { role: "AI Engineer", percentage: 50 },
          { role: "Marketing SME", percentage: 50 },
        ],
      },
      {
        id: "marketing-2",
        name: "Campaign performance tracking",
        description: "Real-time tracking and analysis of marketing campaign performance.",
        timeInWeeks: 1.5,
        cost: 3500,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Marketing SME", percentage: 40 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
      {
        id: "marketing-3",
        name: "Market trend analysis",
        description: "AI-powered analysis of market trends and consumer behavior.",
        timeInWeeks: 2,
        cost: 4000,
        resources: [
          { role: "AI Engineer", percentage: 50 },
          { role: "Marketing SME", percentage: 30 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
      {
        id: "marketing-4",
        name: "Sales forecasting",
        description: "Predictive sales forecasting based on historical data and market trends.",
        timeInWeeks: 1.5,
        cost: 3500,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Marketing SME", percentage: 40 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
      {
        id: "marketing-5",
        name: "Customer segmentation",
        description: "Automated customer segmentation for targeted marketing campaigns.",
        timeInWeeks: 1,
        cost: 2500,
        resources: [
          { role: "AI Engineer", percentage: 50 },
          { role: "Marketing SME", percentage: 30 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
    ],
    dependencies: [
      {
        id: "marketing-rag",
        name: "Marketing Knowledge RAG",
        description: "Specialized Retrieval Augmented Generation for marketing content and customer data",
        timeInWeeks: 2,
        cost: 8000,
        resources: [
          { role: "AI Engineer", percentage: 60 },
          { role: "Data Engineer", percentage: 40 },
        ],
        required: true,
      },
    ],
  },
  {
    id: "legal",
    name: "Legal Agent",
    category: "horizontal",
    type: "Legal",
    description:
      "Assists legal departments in ensuring contract compliance, clause analysis, and legislative tracking through automation.",
    avatar: "/scales-of-justice-abstract.png",
    price: 18000,
    timeInWeeks: 7,
    resources: [
      { role: "AI Engineer", percentage: 40 },
      { role: "Legal SME", percentage: 30 },
      { role: "Data Engineer", percentage: 20 },
      { role: "QA", percentage: 10 },
    ],
    tasks: [
      "Automated NDA Alerts",
      "Contract Template Generation",
      "Clause Compliance Alerts",
      "Compliance Advisor",
      "Real-Time NDA Tracking",
      "Interactive Clause Explanation",
      "Contract Clause Search and Compliance Check",
      "Legislation Monitoring and Relevance",
    ],
    services: [
      {
        id: "legal-1",
        name: "Contract analysis and management",
        description: "AI-powered analysis of contracts to identify key terms, obligations, risks, and opportunities.",
        timeInWeeks: 2,
        cost: 5000,
        resources: [
          { role: "AI Engineer", percentage: 50 },
          { role: "Legal SME", percentage: 50 },
        ],
      },
      {
        id: "legal-2",
        name: "Legal document review and generation",
        description: "Automated review and generation of legal documents with consistency and compliance checks.",
        timeInWeeks: 1.5,
        cost: 4000,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Legal SME", percentage: 40 },
          { role: "QA", percentage: 20 },
        ],
      },
      {
        id: "legal-3",
        name: "Compliance monitoring and reporting",
        description:
          "Continuous monitoring of regulatory changes and compliance requirements with automated reporting.",
        timeInWeeks: 2,
        cost: 4500,
        resources: [
          { role: "AI Engineer", percentage: 30 },
          { role: "Legal SME", percentage: 50 },
          { role: "QA", percentage: 20 },
        ],
      },
      {
        id: "legal-4",
        name: "Legal research and case analysis",
        description: "AI-assisted legal research and case analysis to identify relevant precedents and insights.",
        timeInWeeks: 2,
        cost: 5000,
        resources: [
          { role: "AI Engineer", percentage: 50 },
          { role: "Legal SME", percentage: 50 },
        ],
      },
      {
        id: "legal-5",
        name: "Intellectual property management",
        description: "Manage and protect intellectual property assets with AI-powered monitoring and analysis.",
        timeInWeeks: 1.5,
        cost: 4000,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Legal SME", percentage: 40 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
    ],
    dependencies: [
      {
        id: "legal-rag",
        name: "Legal Document RAG",
        description: "Specialized Retrieval Augmented Generation for legal documents and precedents",
        timeInWeeks: 2,
        cost: 9000,
        resources: [
          { role: "AI Engineer", percentage: 60 },
          { role: "Data Engineer", percentage: 40 },
        ],
        required: true,
      },
    ],
  },
]

// Business agents (formerly industry agents)
export const businessAgents: Agent[] = [
  {
    id: "emergency-response",
    name: "Emergency Response Coordination Agent",
    category: "industry",
    type: "Government",
    description: "Coordinates emergency response efforts with real-time data analysis and resource allocation.",
    avatar: "/emergency-response-icon.png",
    price: 22000,
    timeInWeeks: 8,
    resources: [
      { role: "AI Engineer", percentage: 40 },
      { role: "Government SME", percentage: 30 },
      { role: "Data Engineer", percentage: 20 },
      { role: "QA", percentage: 10 },
    ],
    tasks: [
      "Real-time Emergency Monitoring",
      "Resource Allocation Optimization",
      "Incident Response Coordination",
      "Public Alert Management",
      "Post-incident Analysis",
    ],
    services: [
      {
        id: "emergency-1",
        name: "Real-time emergency monitoring",
        description: "AI-powered monitoring of emergency situations with real-time data analysis.",
        timeInWeeks: 2.5,
        cost: 6000,
        resources: [
          { role: "AI Engineer", percentage: 50 },
          { role: "Government SME", percentage: 30 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
      {
        id: "emergency-2",
        name: "Resource allocation optimization",
        description: "Optimize allocation of emergency resources based on real-time data and historical patterns.",
        timeInWeeks: 2,
        cost: 5500,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Government SME", percentage: 40 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
      {
        id: "emergency-3",
        name: "Public alert management",
        description: "Automated management of public alerts and notifications during emergencies.",
        timeInWeeks: 1.5,
        cost: 4000,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Government SME", percentage: 40 },
          { role: "QA", percentage: 20 },
        ],
      },
    ],
    dependencies: [
      {
        id: "emergency-rag",
        name: "Emergency Response RAG",
        description: "Specialized Retrieval Augmented Generation for emergency protocols and procedures",
        timeInWeeks: 2,
        cost: 9000,
        resources: [
          { role: "AI Engineer", percentage: 60 },
          { role: "Data Engineer", percentage: 40 },
        ],
        required: true,
      },
    ],
  },
  {
    id: "urban-planning",
    name: "Urban Planning Agent",
    category: "industry",
    type: "Government",
    description: "Assists urban planners with data-driven insights for sustainable and efficient city development.",
    avatar: "/urban-planning-icon.png",
    price: 20000,
    timeInWeeks: 7,
    resources: [
      { role: "AI Engineer", percentage: 40 },
      { role: "Urban Planning SME", percentage: 30 },
      { role: "Data Engineer", percentage: 20 },
      { role: "QA", percentage: 10 },
    ],
    tasks: [
      "Traffic Flow Optimization",
      "Land Use Analysis",
      "Infrastructure Planning",
      "Environmental Impact Assessment",
      "Public Space Utilization",
    ],
    services: [
      {
        id: "urban-1",
        name: "Traffic flow optimization",
        description: "AI-powered analysis and optimization of urban traffic patterns.",
        timeInWeeks: 2,
        cost: 5000,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Urban Planning SME", percentage: 40 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
      {
        id: "urban-2",
        name: "Land use analysis",
        description: "Data-driven analysis of land use patterns and optimization recommendations.",
        timeInWeeks: 2,
        cost: 5500,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Urban Planning SME", percentage: 40 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
      {
        id: "urban-3",
        name: "Infrastructure planning",
        description: "AI-assisted planning of urban infrastructure based on population needs and growth projections.",
        timeInWeeks: 2.5,
        cost: 6000,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Urban Planning SME", percentage: 40 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
    ],
    dependencies: [
      {
        id: "urban-rag",
        name: "Urban Planning RAG",
        description: "Specialized Retrieval Augmented Generation for urban planning data and regulations",
        timeInWeeks: 2,
        cost: 8000,
        resources: [
          { role: "AI Engineer", percentage: 60 },
          { role: "Data Engineer", percentage: 40 },
        ],
        required: true,
      },
    ],
  },
  {
    id: "healthcare",
    name: "Healthcare Agent",
    category: "industry",
    type: "Healthcare",
    description:
      "Optimizes patient care through medical imaging analysis, remote monitoring, and clinical trial matching.",
    avatar: "/interconnected-healthcare.png",
    price: 20000,
    timeInWeeks: 8,
    defaultSelected: true,
    resources: [
      { role: "AI Engineer", percentage: 40 },
      { role: "Healthcare SME", percentage: 30 },
      { role: "Data Engineer", percentage: 20 },
      { role: "QA", percentage: 10 },
    ],
    tasks: [
      "Medical Imaging Analysis",
      "Remote Patient Monitoring",
      "Clinical Trial Matching",
      "Mental Health Support",
      "Patient Data Analysis",
      "Treatment Recommendation Support",
    ],
    services: [
      {
        id: "healthcare-1",
        name: "Patient data analysis and insights",
        description: "Analyze patient data to identify patterns, risks, and treatment opportunities.",
        timeInWeeks: 2,
        cost: 5000,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Healthcare SME", percentage: 40 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
      {
        id: "healthcare-2",
        name: "Treatment recommendation support",
        description: "AI-assisted treatment recommendations based on patient data and medical literature.",
        timeInWeeks: 2.5,
        cost: 6000,
        resources: [
          { role: "AI Engineer", percentage: 50 },
          { role: "Healthcare SME", percentage: 50 },
        ],
      },
      {
        id: "healthcare-3",
        name: "Medical research assistance",
        description: "AI-powered research assistant that analyzes medical literature and clinical data.",
        timeInWeeks: 2,
        cost: 5500,
        resources: [
          { role: "AI Engineer", percentage: 50 },
          { role: "Healthcare SME", percentage: 50 },
        ],
      },
      {
        id: "healthcare-4",
        name: "Healthcare compliance management",
        description: "Monitor and manage healthcare compliance requirements with automated alerts and reporting.",
        timeInWeeks: 1.5,
        cost: 4000,
        resources: [
          { role: "AI Engineer", percentage: 30 },
          { role: "Healthcare SME", percentage: 50 },
          { role: "QA", percentage: 20 },
        ],
      },
      {
        id: "healthcare-5",
        name: "Patient engagement optimization",
        description: "Improve patient engagement with personalized communication and education materials.",
        timeInWeeks: 2,
        cost: 4500,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Healthcare SME", percentage: 40 },
          { role: "QA", percentage: 20 },
        ],
      },
    ],
    dependencies: [
      {
        id: "healthcare-rag",
        name: "Medical Knowledge RAG",
        description: "Specialized Retrieval Augmented Generation for medical literature and patient records",
        timeInWeeks: 2.5,
        cost: 10000,
        resources: [
          { role: "AI Engineer", percentage: 60 },
          { role: "Data Engineer", percentage: 40 },
        ],
        required: true,
      },
      {
        id: "healthcare-integration",
        name: "Healthcare Systems Integration",
        description: "Integration with electronic health records and medical systems",
        timeInWeeks: 2,
        cost: 8000,
        resources: [
          { role: "Data Engineer", percentage: 60 },
          { role: "Backend Developer", percentage: 40 },
        ],
      },
    ],
  },
  {
    id: "financial-services",
    name: "Financial Services Agent",
    category: "industry",
    type: "Financial Services",
    description:
      "Enhances financial operations with credit risk assessment, trading strategies, and regulatory compliance automation.",
    avatar: "/interconnected-finance.png",
    price: 22000,
    timeInWeeks: 8,
    resources: [
      { role: "AI Engineer", percentage: 40 },
      { role: "Finance SME", percentage: 30 },
      { role: "Data Engineer", percentage: 20 },
      { role: "QA", percentage: 10 },
    ],
    tasks: [
      "Credit Risk Assessment",
      "Trading Strategy Optimization",
      "Regulatory Compliance Automation",
      "Anti-Money Laundering Detection",
      "Investment and Wealth Management",
      "Fraud Detection and Prevention",
    ],
    services: [
      {
        id: "finserv-1",
        name: "Fraud detection and prevention",
        description:
          "AI-powered fraud detection system that identifies suspicious patterns and activities in real-time.",
        timeInWeeks: 2.5,
        cost: 6000,
        resources: [
          { role: "AI Engineer", percentage: 50 },
          { role: "Finance SME", percentage: 30 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
      {
        id: "finserv-2",
        name: "Credit risk assessment",
        description: "Evaluate credit risk using AI models trained on historical data and market indicators.",
        timeInWeeks: 2,
        cost: 5500,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Finance SME", percentage: 40 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
      {
        id: "finserv-3",
        name: "Customer financial advisory",
        description: "AI-assisted financial advisory services with personalized recommendations and insights.",
        timeInWeeks: 2,
        cost: 5000,
        resources: [
          { role: "AI Engineer", percentage: 50 },
          { role: "Finance SME", percentage: 50 },
        ],
      },
      {
        id: "finserv-4",
        name: "Investment portfolio optimization",
        description: "Optimize investment portfolios using AI models that balance risk and return objectives.",
        timeInWeeks: 2.5,
        cost: 6000,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Finance SME", percentage: 40 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
      {
        id: "finserv-5",
        name: "Insurance claims processing",
        description: "Automate insurance claims processing with AI-powered document analysis and fraud detection.",
        timeInWeeks: 2,
        cost: 5000,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Finance SME", percentage: 40 },
          { role: "QA", percentage: 20 },
        ],
      },
    ],
    dependencies: [
      {
        id: "finserv-rag",
        name: "Financial Services RAG",
        description: "Specialized Retrieval Augmented Generation for financial regulations and market data",
        timeInWeeks: 2,
        cost: 9000,
        resources: [
          { role: "AI Engineer", percentage: 60 },
          { role: "Data Engineer", percentage: 40 },
        ],
        required: true,
      },
      {
        id: "finserv-ml",
        name: "Financial ML Models",
        description: "Specialized machine learning models for fraud detection and risk assessment",
        timeInWeeks: 3,
        cost: 12000,
        resources: [
          { role: "AI Engineer", percentage: 70 },
          { role: "Data Engineer", percentage: 30 },
        ],
      },
    ],
  },
  {
    id: "manufacturing",
    name: "Manufacturing Agent",
    category: "industry",
    type: "Manufacturing",
    description:
      "Improves manufacturing efficiency through predictive maintenance, quality control, and demand forecasting.",
    avatar: "/automated-assembly-line.png",
    price: 18000,
    timeInWeeks: 7,
    resources: [
      { role: "AI Engineer", percentage: 40 },
      { role: "Manufacturing SME", percentage: 30 },
      { role: "Data Engineer", percentage: 20 },
      { role: "QA", percentage: 10 },
    ],
    tasks: [
      "Predictive Maintenance",
      "Quality Control Automation",
      "Demand Forecasting",
      "Production Line Optimization",
      "Supply Chain Optimization",
      "Inventory Management",
    ],
    services: [
      {
        id: "manufacturing-1",
        name: "Production line optimization",
        description: "Optimize production lines using AI models that analyze efficiency, quality, and throughput.",
        timeInWeeks: 2,
        cost: 5000,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Manufacturing SME", percentage: 40 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
      {
        id: "manufacturing-2",
        name: "Predictive maintenance",
        description: "Predict equipment failures before they occur to minimize downtime and maintenance costs.",
        timeInWeeks: 2.5,
        cost: 5500,
        resources: [
          { role: "AI Engineer", percentage: 50 },
          { role: "Manufacturing SME", percentage: 30 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
      {
        id: "manufacturing-3",
        name: "Quality control automation",
        description: "Automate quality control processes using computer vision and machine learning.",
        timeInWeeks: 2,
        cost: 5000,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Manufacturing SME", percentage: 40 },
          { role: "QA", percentage: 20 },
        ],
      },
      {
        id: "manufacturing-4",
        name: "Supply chain optimization",
        description: "Optimize supply chain operations with AI-powered demand forecasting and inventory management.",
        timeInWeeks: 2,
        cost: 4500,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Manufacturing SME", percentage: 30 },
          { role: "Data Engineer", percentage: 30 },
        ],
      },
      {
        id: "manufacturing-5",
        name: "Inventory management",
        description: "AI-powered inventory management that optimizes stock levels and reduces carrying costs.",
        timeInWeeks: 1.5,
        cost: 4000,
        resources: [
          { role: "AI Engineer", percentage: 30 },
          { role: "Manufacturing SME", percentage: 40 },
          { role: "Data Engineer", percentage: 30 },
        ],
      },
    ],
    dependencies: [
      {
        id: "manufacturing-rag",
        name: "Manufacturing Knowledge RAG",
        description:
          "Specialized Retrieval Augmented Generation for manufacturing processes and equipment documentation",
        timeInWeeks: 2,
        cost: 8000,
        resources: [
          { role: "AI Engineer", percentage: 60 },
          { role: "Data Engineer", percentage: 40 },
        ],
        required: true,
      },
      {
        id: "manufacturing-iot",
        name: "IoT Integration",
        description: "Integration with IoT devices and sensors for real-time monitoring",
        timeInWeeks: 2,
        cost: 9000,
        resources: [
          { role: "Data Engineer", percentage: 50 },
          { role: "Backend Developer", percentage: 50 },
        ],
      },
    ],
  },
  {
    id: "energy",
    name: "Energy Management Agent",
    category: "industry",
    type: "Energy",
    description: "Optimizes energy distribution with grid load balancing and renewable energy integration.",
    avatar: "/energy-management-icon.png",
    price: 19000,
    timeInWeeks: 7,
    resources: [
      { role: "AI Engineer", percentage: 40 },
      { role: "Energy SME", percentage: 30 },
      { role: "Data Engineer", percentage: 20 },
      { role: "QA", percentage: 10 },
    ],
    tasks: [
      "Grid Load Balancing",
      "Renewable Energy Optimization",
      "Energy Consumption Forecasting",
      "Infrastructure Monitoring",
      "Maintenance Scheduling",
    ],
    services: [
      {
        id: "energy-1",
        name: "Grid load balancing",
        description: "AI-powered balancing of energy grid loads for optimal efficiency and stability.",
        timeInWeeks: 2.5,
        cost: 6000,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Energy SME", percentage: 40 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
      {
        id: "energy-2",
        name: "Renewable energy optimization",
        description: "Optimize integration and utilization of renewable energy sources in the power grid.",
        timeInWeeks: 2,
        cost: 5500,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Energy SME", percentage: 40 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
      {
        id: "energy-3",
        name: "Energy consumption forecasting",
        description: "Predict energy consumption patterns to optimize generation and distribution.",
        timeInWeeks: 2,
        cost: 5000,
        resources: [
          { role: "AI Engineer", percentage: 50 },
          { role: "Energy SME", percentage: 30 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
    ],
    dependencies: [
      {
        id: "energy-rag",
        name: "Energy Management RAG",
        description: "Specialized Retrieval Augmented Generation for energy management data and regulations",
        timeInWeeks: 2,
        cost: 8000,
        resources: [
          { role: "AI Engineer", percentage: 60 },
          { role: "Data Engineer", percentage: 40 },
        ],
        required: true,
      },
    ],
  },
  {
    id: "retail",
    name: "Retail Optimization Agent",
    category: "industry",
    type: "Retail",
    description:
      "Enhances retail operations through store layout optimization, inventory management, and customer insights.",
    avatar: "/retail-optimization-icon.png",
    price: 17000,
    timeInWeeks: 6,
    resources: [
      { role: "AI Engineer", percentage: 40 },
      { role: "Retail SME", percentage: 30 },
      { role: "Data Engineer", percentage: 20 },
      { role: "QA", percentage: 10 },
    ],
    tasks: [
      "Store Layout Optimization",
      "Demand Forecasting",
      "Customer Segmentation",
      "Inventory Optimization",
      "Pricing Strategy Analysis",
    ],
    services: [
      {
        id: "retail-1",
        name: "Store layout optimization",
        description: "AI-powered optimization of store layouts for improved customer experience and sales.",
        timeInWeeks: 2,
        cost: 5000,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Retail SME", percentage: 40 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
      {
        id: "retail-2",
        name: "Demand forecasting",
        description: "Predict product demand patterns to optimize inventory and reduce stockouts.",
        timeInWeeks: 2,
        cost: 5500,
        resources: [
          { role: "AI Engineer", percentage: 50 },
          { role: "Retail SME", percentage: 30 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
      {
        id: "retail-3",
        name: "Customer segmentation",
        description: "AI-powered customer segmentation for personalized marketing and product recommendations.",
        timeInWeeks: 1.5,
        cost: 4000,
        resources: [
          { role: "AI Engineer", percentage: 40 },
          { role: "Retail SME", percentage: 40 },
          { role: "Data Engineer", percentage: 20 },
        ],
      },
    ],
    dependencies: [
      {
        id: "retail-rag",
        name: "Retail Analytics RAG",
        description: "Specialized Retrieval Augmented Generation for retail analytics and customer data",
        timeInWeeks: 2,
        cost: 7000,
        resources: [
          { role: "AI Engineer", percentage: 60 },
          { role: "Data Engineer", percentage: 40 },
        ],
        required: true,
      },
    ],
  },
]

export const agentCategories: AgentCategory[] = [
  {
    id: "horizontal",
    name: "Horizontal Enterprise Agent Pack",
    agents: horizontalAgents,
  },
  {
    id: "industry",
    name: "Industry-Specific Agent Pack",
    agents: businessAgents,
  },
  {
    id: "custom",
    name: "Customized Agents",
    agents: [], // Initially empty, will be populated when users create custom agents
  },
]
